### ISSUE TITLE
Readme Addition

### ISSUE THREAD

**Issue by Kaphaalor** [mobizt/Firebase-Arduino-WiFi101#11]
Readme Instructions do not mention, that the google.com certificate needs to be installed.

---
Open the Firmware update project (File -> Examples -> WiFi101 -> FirmwareUpdater)
Load it into the Arduino
Open the FirmwareUpdate Tool (Tools -> WiFi101 / WiFiNINA Firmware Updater)
Add the "google.com:443" SSL root domain to the arduino
---

Took me several hours to debug, why the connection to firebase got declined and I don't want others to live through this struggle.

**Comment by mobizt** [comment]
This is the issue of Arduino firmware, no matter you use this WiFiNiNA library to connect to any site, it will not pass the certificate verification process as the firmware does not allow certificate verification bypass option.

You should comment this on the WiFiNiNA firmware repo.

**Comment by mobizt** [comment]
When server or root certificate stored on u-blox ESP32 side expired, you will never known it, you need to update the certificate indirectly using Arduino IDE when connection to server failed instead of doing certificate renewal in your own code.
