### ISSUE TITLE
Connection Refused using an Arduino MKR1000 board

### ISSUE THREAD

**Issue by Barberto906** [mobizt/Firebase-Arduino-WiFi101#4]
First of all thank you for the really useful library!
I have tried to run the Basic.ino example to see if my firebase database and the MKR1000 were working properly, but form the serial monitor of arduino I keep receiving a "connection refused" message. 
I did check my firebase host and authorization. I have tried to use the hotspot on my phone as well to change wifi, but nothing worked so far. 
Any suggestion on why it refuse to work ?
(the code I'm using is just the basic.ino example with my host, auth, ssid and password)

**Comment by mobizt** [comment]
This may be the SSL certificate issue. 
Please try to update firmware in Arduino IDE, go to Tools -> WiFi101 / WiFiNINA Firmware Updater

**Comment by Barberto906** [comment]
Sorry for my late response, I couldn't try earlier. 
Anyway it worked, thank you so much !!
