### ISSUE TITLE
Error in the getInt example

### ISSUE THREAD

**Issue by will-sloan** [mobizt/Firebase-Arduino-WiFi101#5]
In the example in the README.md, there is an extra bracket. 
`if (firebaseData.dataType() == "int")) {
      val = firebaseData.intData();
      Serial.println(val);
    }`

should be :
 `if (firebaseData.dataType() == "int") {
      val = firebaseData.intData();
      Serial.println(val);
    }`

**Comment by mobizt** [comment]
It is typo and already known it. You should follow the examples instead.
