### ISSUE TITLE
Connection refused on example code

### ISSUE THREAD

**Issue by crysxd** [mobizt/Firebase-Arduino-WiFi101#7]
Hi, I get a connection refused on the example code (basic). I filled in my project id, database secret (tested) and wifi data. The MKR1000 connects to wifi and is listed at the router. 

Any idea how I can debug this? I use version 1.1.3

**Comment by crysxd** [comment]
Never mind! My firmware was outdated. After trying for over 2h I just found out....
If anyone has the same issue: https://www.arduino.cc/en/Tutorial/FirmwareUpdater

Maybe it's a good idea to mention this either in the error message or here in the docs :)

**Comment by mobizt** [comment]
Ok thanks

**Comment by this-is-pat** [comment]
Hi! I'm experiencing the same issue on the example code (connection refused). The firmware is updated to version 19.6.1 and the MKR1000 does connect to WiFi (it shows connected with IP...). I changed the database secret a couple of times still the same problem though.

**Comment by mobizt** [comment]
I library was test with my MKR1000 before I post this comment which it works normally without the problem.

Please try to upload certificate and also add the domain of your Firebase host.

**Comment by mobizt** [comment]
@InnerWar01 

The library was test with my MKR1000 before I post this comment which it works normally without the problem.

Please try to upload certificate and also add the domain of your Firebase host.

**Comment by this-is-pat** [comment]
The Firebase host that I have is _myproject-default-rtdb.europe-west1.firebasedatabase.app_ and for the certificate I am not sure which one to upload. Is it the _authDomain_?

**Comment by mobizt** [comment]
@InnerWar01 
https://www.arduino.cc/en/Tutorial/FirmwareUpdater#certificate-uploading

Click add domain button and add your project host **myproject-default-rtdb.europe-west1.firebasedatabase.app**

**Comment by this-is-pat** [comment]
Uploaded the certificate but still get a connection refused.

**Comment by mobizt** [comment]
@InnerWar01
No internet connectivity, check your router or WiFi hotspot.

Make sure access point is for 2.4G WiFi instead of 5G.

**Comment by this-is-pat** [comment]
I'm using a mobile hotspot, it says the broadcast channel uses 2.4GHz and the MKR1000 appears as connected devices.

**Comment by mobizt** [comment]
@InnerWar01

Let try to update the WiFi101 library.

You must provide the valid host in FIREBASE_HOST e.g. myproject-default-rtdb.europe-west1.firebasedatabase.app without schemes (https://) and backslash at the end.

For FIREBASE_AUTH, try to renew your database secret from Firebase project console.

If you're still cannot connect, the issue is on your device hardware.

Try to change the shorter USB cable to provide more stable power.

**Comment by this-is-pat** [comment]
Must be a hardware issue then, thanks for the help!

**Comment by gachet** [comment]
> @InnerWar01 https://www.arduino.cc/en/Tutorial/FirmwareUpdater#certificate-uploading
> 
> Click add domain button and add your project host **myproject-default-rtdb.europe-west1.firebasedatabase.app**

Nice it works, thanks a lot, It would have been better to explain this in the Readme or in te comments of Basic example, Thanks again,
