### ISSUE TITLE
Getting bad request

### ISSUE THREAD

**Issue by hetkpatel** [mobizt/Firebase-Arduino-WiFi101#8]
Even after updating the firmware of my MKR1000, I get `bad request` as the `errorReason()`. Is there a way to get more detail on the `errorReason()` function; maybe an error code or solution?

**Comment by mobizt** [comment]
The bad request  is from many reasons:

- FIREBASE_HOST is not valid. Check it should not end with  / and should not start with http://
- FIREBASE_AUTH is not valid.
- You set or push the JSON serialized string which contains some invalid tokens or invalid characters that cause the invalid JSON.
- The node path parameter contains invalid tokens or empty.

The above list is total possible reasons of this error.

It's better to post the code here to check.

**Comment by hetkpatel** [comment]
Yea, here's the code:
```
#include "Firebase_Arduino_WiFi101.h"

FirebaseData firebaseData;

void setup() {
    Serial.begin(115200);
    delay(30000);
    Serial.println("Starting program");
    int status = WL_IDLE_STATUS;
    while (status != WL_CONNECTED){
        status = WiFi.begin(WIFI_SSID, WIFI_PASS);
        delay(300);
    }
    Firebase.begin(FIREBASE_URL, FIREBASE_TOKEN, WIFI_SSID, WIFI_PASS);

    String firstName;
    if (Firebase.getString(firebaseData, "firstName")) {
        firstName = firebaseData.stringData();
        Serial.println(firstName);
    } else {
        Serial.println(firebaseData.errorReason());
    }
}

void loop() {}
```
Things I've check so far:
1. `FIREBASE_URL` starts with `https` and does not include a trailing `/`
2. I assume `FIREBASE_AUTH` is my `FIREBASE_TOKEN` which is valid.
3. I've tried connecting it to other WiFi sources like my phone's hotspot but still returns the same error.

**Comment by hetkpatel** [comment]
Solved it! Thanks.
