### ISSUE TITLE
Adafruit Feather M0 WiFi issue

### ISSUE THREAD

**Issue by paulllleon** [mobizt/Firebase-Arduino-WiFi101#9]

**Comment by mobizt** [comment]
Please post the error message.

Update Firmware first
https://learn.adafruit.com/adafruit-feather-m0-wifi-atwinc1500/updating-firmware

Then update certificate
https://learn.adafruit.com/adafruit-feather-m0-wifi-atwinc1500/updating-ssl-certificates

Don't forget to add your firebase domain when update certificate.

This is the issue of device which uses WiFiNINA you can follow.
https://github.com/mobizt/Firebase-Arduino-WiFiNINA/issues/18

**Comment by paulllleon** [comment]
Thank you very much, it was indeed a setificiat issue.
